### PR TITLE
Bug fix: only run server/client event handlers when the server/client is available

### LINKED ISSUE #18: ServerState/ClientState conflict with disabling plugins
The methods `add_server_event_with()` and `add_client_event_with()` depend on both `ServerState` and `ClientState`. This means if you disable the server or client plugins then the program will crash on update with error 'resource not found' for the missing state.

The doc test demoing plugin disabling doesn't actually try to update the app. Here is an updated test that fails:

```rust
# use bevy::prelude::*;
# use bevy_replicon::prelude::*;
# let mut app = App::new();
app.add_plugins(MinimalPlugins).add_plugins(
    ReplicationPlugins
        .build()
        .disable::<ClientPlugin>()
        .set(ServerPlugin { tick_policy: TickPolicy::MaxTickRate(60) }),
);

# #[derive(Debug)]
# struct X;
# app.add_server_event_with::<X, _, _>(||{}, ||{});
# app.update();
```

### PR DESCRIPTION
**Pull request by UkoeHB**
Fixes #18

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -36,6 +36,22 @@ app.add_plugins(MinimalPlugins).add_plugins(
...
+# let mut app = App::new();
+# app.add_plugins(MinimalPlugins).add_plugins(
+#    ReplicationPlugins
+#        .build()
+#        .disable::<ServerPlugin>()
+#        .set(ServerPlugin { tick_policy: TickPolicy::MaxTickRate(60) }),
+# );
+#
+# app.add_server_event_with::<X, _, _>(||{}, ||{});
+# app.update();
```
Comment (Shatur) [inline src/lib.rs:54]: Could you move into unit test to `server_event` module and add the same for `client_event`?

**Review by Shatur — CHANGES_REQUESTED** [review]

**Comment by Shatur** [comment]
Thanks!
